GET http://localhost:3003/api/blogs

### separator
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxvIiwiaWQiOiI2YTIzNjcyM2Q2ZjFjNWM3Y2VhYjgzZTAiLCJpYXQiOjE3ODA3ODQxNzgsImV4cCI6MTc4MDc4Nzc3OH0.icUfY7CVMySx1Ut7YyB6Zo-U9Pg6eiBJHLePjfqGjBI

{  "title": "OOO",
  "author": "sadad",
  "url": "https://localhost:3003/rrrrrr",
  "likes": 11
}

###

POST  http://localhost:3003/api/login
Content-Type: application/json

{"username":"hello",
"password":"hello"}

