DELETE http://localhost:3003/api/blogs/6a15dd983364f16470c2bd64
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxvIiwiaWQiOiI2YTIzNjcyM2Q2ZjFjNWM3Y2VhYjgzZTAiLCJpYXQiOjE3ODEwNDM2OTcsImV4cCI6MTc4MTA0NzI5N30.I8d5XoIdjpflrhEX5sXWuzG31ZQMhKjDcZRz463onNo


###

PUT http://localhost:3003/api/blogs/6a14929e1c47a15f2b379b7d
content-type: application/json

{  "title": "POOOOOOO",
  "author": "MEOW",
  "url": "https://localhost:3003/MEEEEEOWWWW",
  "likes": 128364640860418
}

###

POST  http://localhost:3003/api/login
Content-Type: application/json

{"username":"hello",
"password":"hello"}

