GET  http://localhost:3003/api/users
###

POST http://localhost:3003/api/users
Content-Type: application/json

{"username":"meow",
"name":"hi",
"password":"meow123"}

###

POST  http://localhost:3003/api/login
Content-Type: application/json

{"username":"hello",
"password":"hello"}


###
DELETE http://localhost:3003/api/users/6a236723d6f1c5c7ceab83e0